INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15111', 'Matanza de ganado bovino y procesamiento de su carne');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15112', 'Producción y procesamiento de carne de aves de corral');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15113', 'Elaboración de fiambres y embutidos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15114', 'Matanza de ganado excepto el bovino y procesamiento de su carne');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15119', 'Elaboración de subproductos cárnicos ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15120', 'Elaboración y conservación de pescado y productos de pescado');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15131', 'Preparación de conservas de frutas, hortalizas y legumbres');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15132', 'Elaboración de jugos naturales y sus concentrados, de frutas, hortalizas y legumbres');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15133', 'Elaboración de pulpas, jaleas, dulces y mermeladas obtenidos por cocción');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15134', 'Elaboración y preparación de frutas, hortalizas y legumbres deshidratadas o desecadas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15141', 'Elaboración de aceites y grasas vegetales sin refinar y subproductos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15142', 'Elaboración de aceites y grasas vegetales refinadas y subproductos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15143', 'Preparación de tortas y producción de harinas y productos residuales de la producción de aceite');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15201', 'Elaboración de leches y productos lácteos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15202', 'Elaboración de helados');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15203', 'Elaboración de quesos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15311', 'Preparación y molienda de trigo');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15312', 'Preparación de arroz');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15313', 'Preparación y molienda de otros cereales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15314', 'Elaboración de alimentos medíante el tostado o insuflación de granos de cereales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15320', 'Elaboración de alimentos y productos derivados del almidón');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15330', 'Elaboración de alimentos preparados para animales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15411', 'Elaboración de pan');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15412', 'Elaboración de galletas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15419', 'Elaboración de otros productos de panadería y pastelería ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15420', 'Elaboración de azúcar');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15431', 'Elaboración de cacao y productos de cacao');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15432', 'Elaboración de chocolates y productos de chocolate');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15433', 'Elaboración de productos de confitería');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15441', 'Elaboración de pastas alimenticias secas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15442', 'Elaboración de pastas rellenas, cocidas o sin cocer y otros productos similares');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15491', 'Tostado, torrado y molienda de café');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15492', 'Elaboración de té, hierbas aromáticas y especias');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15499', 'Elaboración de productos alimenticios ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15511', 'Destilación de alcohol etílico');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15512', 'Destilación, rectificación y mezclas de bebidas espirituosas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15521', 'Elaboración de vinos, bebidas fermentadas pero no destiladas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15530', 'Elaboración de bebidas malteadas y de malta');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15541', 'Elaboración de bebidas gaseosas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15542', 'Elaboración de aguas minerales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('15543', 'Elaboración de hielo y otras bebidas no alcohólicas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('16000', 'Elaboración de productos de tabaco');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17111', 'Preparación, cardado y peinado de fibras textiles');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17112', 'Fabricación de hilados e hilos para tejido y costura');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17113', 'Fabricación de tejidos de fibras textiles incluso sus mezclas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17120', 'Acabado de productos textiles');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17210', 'Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17220', 'Fabricación de tapices y alfombras');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17230', 'Fabricación de cuerdas, cordeles, bramantes y redes');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17290', 'Fabricación de otros productos textiles ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17301', 'Fabricación de medias');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17302', 'Fabricación de chompas y artículos similares de punto');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('17309', 'Fabricación de tejidos y artículos de punto ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('18101', 'Fabricación de prendas de vestir confeccionadas, para hombres, mujeres y niños');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('18102', 'Fabricación de ropa de trabajo, uniformes y guardapolvos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('18103', 'Fabricación de ropa deportiva');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('18109', 'Fabricación de prendas de vestir de cuero y otras prendas ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('18200', 'Adobo y teñido de pieles; fabricación de artículos de piel');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('19110', 'Curtido de cueros');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('19120', 'Fabricación de artículos de marroquinería, talabartería');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('19201', 'Fabricación de calzado de cuero, excepto ortopédico y de asbesto');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('19202', 'Fabricación de calzado de tela, plástico, goma, caucho y otros materiales, excepto calzado ortopédico y de asbesto');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('19203', 'Fabricación de partes de calzado');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('20100', 'Aserrado y cepillado de madera');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('20210', 'Fabricación de hojas de madera para enchapado; de tableros contrachapados, tableros laminados, tableros de  
partículas y otros tableros y paneles');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('20210', 'Fabricación de hojas de madera para enchapado; de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('20220', 'Fabricación de partes y piezas de carpintería para edificios y construcciones');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('20230', 'Fabricación de recipientes de madera');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('20290', 'Fabricación de otros productos de madera; de artículos de corcho, paja y materiales trenzables ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('21010', 'Fabricación de pasta de madera, papel y cartón');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('21020', 'Fabricación de papel y cartón ondulado y de envases de papel y cartón');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('21091', 'Fabricación de artículos de papel de uso doméstico e higiénico');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('21099', 'Fabricación de otros artículos de papel y cartón ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22110', 'Edición de libros, folletos, partituras y otras publicaciones');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22120', 'Edición de periódicos, revistas y publicaciones periódicas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22130', 'Edición de grabaciones');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22190', 'Otras actividades de edición');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22210', 'Actividades de impresión');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22220', 'Actividades de servicios relacionadas con la impresión');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('22300', 'Reproducción de grabaciones');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24111', 'Fabricación de gases industriales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24112', 'Fabricación de sustancias químicas básicas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24120', 'Fabricación de abonos y compuestos de nitrógeno');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24130', 'Fabricación de plásticos en formas primarias y de caucho sintético');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24210', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24220', 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24230', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24241', 'Fabricación de jabones y detergentes');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24242', 'Fabricación de cosméticos, perfumes, productos de higiene y tocador');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24243', 'Fabricación de preparados para limpiar y pulir');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24290', 'Fabricación de otros productos químicos ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('24300', 'Fabricación de fibras manufacturadas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('25110', 'Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('25190', 'Fabricación de otros productos de caucho');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('25201', 'Fabricación de envases plásticos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('25209', 'Fabricación de productos plásticos en formas básicas y artículos de plástico ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26101', 'Fabricación de envases de vidrio');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26102', 'Fabricación de vidrio');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26109', 'Fabricación de productos de vidrio ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26911', 'Fabricación de artículos de cerámica de uso doméstico, sanitario y ornamental');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26912', 'Fabricación de otros artículos de cerámica no refractaria para uso no estructural');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26920', 'Fabricación de productos de cerámica refractaria');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26930', 'Fabricación de productos de arcilla y cerámica no refractarias para uso estructural');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26941', 'Fabricación de cemento');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26942', 'Fabricación de cal y yeso');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26950', 'Fabricación de artículos de hormigón, cemento y yeso');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26960', 'Corte, tallado y acabado de la piedra');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('26990', 'Fabricación de otros productos minerales no metálicos ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28110', 'Fabricación de productos metálicos para uso estructural');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28120', 'Fabricación de tanques, depósitos y recipientes de metal');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28130', ' Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28910', 'Forja, prensado, estampado y laminado de metales; pulvimetalurgia');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28920', 'Tratamiento y revestimiento de metales; obras de ingeniería mecánica en general realizadas a cambio de una  retribución o contrata');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28930', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28991', 'Fabricación de envases de productos metálicos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('28999', 'Fabricación de productos metálicos ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29110', 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29120', 'Fabricación de bombas, compresores, grifos y valvulas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29130', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29140', 'Fabricación de hornos; hogares y quemadores');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29150', 'Fabricación de equipo de elevación y manipulación');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29190', 'Fabricación de otros tipos de maquinaria de uso general');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29210', 'Fabricación de maquinaria agropecuaria y forestal');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29220', 'Fabricación de maquinas herramienta');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29230', 'Fabricación de maquinaria metalúrgica');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29240', 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29250', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29270', 'Fabricación de armas y municiones');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29290', 'Fabricación de otros tipos de maquinaria de uso especial');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('29300', 'Fabricación de aparatos de uso doméstico ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('30000', 'Fabricación de maquinaria de oficina, contabilidad e informática');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('31100', 'Fabricación de motores, generadores y transformadores eléctricos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('31200', 'Fabricación de aparatos de distribución y control de energía eléctrica');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('31300', 'Fabricación de hilos y cables aislados');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('31400', 'Fabricación de acumuladores y de pilas y baterías primarias');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('31500', 'Fabricación de lámparas eléctricas y equipo de iluminación');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('31900', 'Fabricación de otros tipos de equipo eléctrico ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('32100', 'Fabricación de tubos, válvulas y de otros componentes electrónicos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('32200', 'Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía con hilos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('32300', 'Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido y vídeo y  
productos conexos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('33120', 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y otros fines, excepto el equipo de  control de procesos industriales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('33130', 'Fabricación de equipo de control de procesos industriales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('33200', 'Fabricación de instrumentos de óptica y equipo fotográfico');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('33300', 'Fabricación de relojes');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('34100', 'Fabricación de vehículos automotores');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('34200', ' Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('34300', 'Fabricación de partes, piezas y accesorios para vehículos automotores y sus motores');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35110', 'Construcción y reparación de buques');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35120', 'Construcción y reparación de embarcaciones de recreo y deporte');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35200', ' Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35300', 'Fabricación de aeronaves y naves espaciales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35910', 'Fabricación de motocicletas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35920', 'Fabricación de bicicletas y de sillones de ruedas para inválidos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('35990', 'Fabricación de otros tipos de equipo de transporte ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36101', 'Fabricación de muebles y partes de muebles, principalmente de madera');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36102', 'Fabricación de muebles, y partes de muebles principalmente de metal');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36103', 'Fabricación de muebles, excepto los que son principalmente de madera y metálicos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36104', 'Fabricación de somieres y colchones');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36910', 'Fabricación de joyas y artículos conexos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36920', 'Fabricación de instrumentos de música');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36930', 'Fabricación de artículos de deporte');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36940', 'Fabricación de juegos y juguetes');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('36990', 'Otras industrias manufactureras ncp');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('37100', 'Reciclamiento de desperdicios y desechos metálicos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('37200', 'Reciclamiento de desperdicios y desechos no metálicos');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('Fraccionadoras', 'Fraccionadoras de la industria de alimentos y bebidas');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('Parques', 'Industriales');
INSERT INTO caeb_diccionario (codigo, descripcion) VALUES ('Reciclamiento', 'Reciclamiento de residuos industriales peligrosos');
